import { DocGenType } from "../models/DocGenType";

export const DOCUMENT_TYPES: Partial<DocGenType>[] = [
  // 1. Admissions & Pré-inscriptions
  { code: 'ADM001', libelle: 'Fiche de candidature', categorie: 'Admissions', moduleSource: 'orientation', signatureRequired: false, dua: '5 ans', autoGenerated: false },
  { code: 'ADM002', libelle: 'Demande d\'admission', categorie: 'Admissions', moduleSource: 'orientation', signatureRequired: true, dua: 'Permanente', autoGenerated: false },
  { code: 'ADM003', libelle: 'Accusé de réception', categorie: 'Admissions', moduleSource: 'orientation', signatureRequired: false, dua: '2 ans', autoGenerated: true },
  { code: 'ADM004', libelle: 'Convocation au concours', categorie: 'Admissions', moduleSource: 'orientation', signatureRequired: false, dua: '1 an', autoGenerated: true },
  { code: 'ADM005', libelle: 'Liste des candidats', categorie: 'Admissions', moduleSource: 'orientation', signatureRequired: false, dua: '5 ans', autoGenerated: true },
  { code: 'ADM006', libelle: 'Résultats d\'admission', categorie: 'Admissions', moduleSource: 'orientation', signatureRequired: true, dua: 'Permanente', autoGenerated: true },
  { code: 'ADM007', libelle: 'Lettre d\'admission', categorie: 'Admissions', moduleSource: 'orientation', signatureRequired: true, dua: 'Permanente', autoGenerated: true },
  { code: 'ADM008', libelle: 'Lettre de refus', categorie: 'Admissions', moduleSource: 'orientation', signatureRequired: true, dua: '5 ans', autoGenerated: true },
  { code: 'ADM009', libelle: 'Décision d\'admission', categorie: 'Admissions', moduleSource: 'orientation', signatureRequired: true, dua: 'Permanente', autoGenerated: true },
  { code: 'ADM010', libelle: 'Procès-verbal d\'admission', categorie: 'Admissions', moduleSource: 'orientation', signatureRequired: true, dua: 'Permanente', autoGenerated: true },

  // 2. Inscriptions administratives
  { code: 'INS001', libelle: 'Fiche d\'inscription', categorie: 'Inscriptions', moduleSource: 'inscription', signatureRequired: true, dua: 'Permanente', autoGenerated: false },
  { code: 'INS002', libelle: 'Bulletin d\'inscription', categorie: 'Inscriptions', moduleSource: 'inscription', signatureRequired: true, dua: 'Permanente', autoGenerated: true },
  { code: 'INS003', libelle: 'Certificat d\'inscription', categorie: 'Inscriptions', moduleSource: 'inscription', signatureRequired: true, dua: 'Permanente', autoGenerated: true },
  { code: 'INS004', libelle: 'Carte d\'étudiant', categorie: 'Inscriptions', moduleSource: 'inscription', signatureRequired: false, dua: '1 an', autoGenerated: true },
  { code: 'INS005', libelle: 'Attestation d\'inscription', categorie: 'Inscriptions', moduleSource: 'inscription', signatureRequired: true, dua: 'Permanente', autoGenerated: true },
  { code: 'INS006', libelle: 'Contrat pédagogique', categorie: 'Inscriptions', moduleSource: 'inscription', signatureRequired: true, dua: 'Permanente', autoGenerated: false },
  { code: 'INS007', libelle: 'Reçu d\'inscription', categorie: 'Inscriptions', moduleSource: 'inscription', signatureRequired: true, dua: '10 ans', autoGenerated: true },
  { code: 'INS008', libelle: 'Liste des inscrits', categorie: 'Inscriptions', moduleSource: 'inscription', signatureRequired: false, dua: '5 ans', autoGenerated: true },
  { code: 'INS009', libelle: 'Registre des inscriptions', categorie: 'Inscriptions', moduleSource: 'inscription', signatureRequired: false, dua: 'Permanente', autoGenerated: true },
  { code: 'INS010', libelle: 'Historique des inscriptions', categorie: 'Inscriptions', moduleSource: 'inscription', signatureRequired: false, dua: 'Permanente', autoGenerated: true },

  // 3. Scolarité
  { code: 'SCO001', libelle: 'Certificat de scolarité', categorie: 'Scolarité', moduleSource: 'scolarite', signatureRequired: true, dua: 'Permanente', autoGenerated: true },
  { code: 'SCO002', libelle: 'Attestation de fréquentation', categorie: 'Scolarité', moduleSource: 'scolarite', signatureRequired: true, dua: 'Permanente', autoGenerated: true },
  { code: 'SCO003', libelle: 'Dossier étudiant', categorie: 'Scolarité', moduleSource: 'scolarite', signatureRequired: false, dua: 'Permanente', autoGenerated: true },
  { code: 'SCO004', libelle: 'Demande de transfert', categorie: 'Scolarité', moduleSource: 'scolarite', signatureRequired: false, dua: '5 ans', autoGenerated: false },
  { code: 'SCO005', libelle: 'Décision de transfert', categorie: 'Scolarité', moduleSource: 'scolarite', signatureRequired: true, dua: 'Permanente', autoGenerated: true },
  { code: 'SCO006', libelle: 'Suspension d\'études', categorie: 'Scolarité', moduleSource: 'scolarite', signatureRequired: true, dua: 'Permanente', autoGenerated: true },
  { code: 'SCO007', libelle: 'Reprise d\'études', categorie: 'Scolarité', moduleSource: 'scolarite', signatureRequired: true, dua: 'Permanente', autoGenerated: true },
  { code: 'SCO008', libelle: 'Radiation', categorie: 'Scolarité', moduleSource: 'scolarite', signatureRequired: true, dua: 'Permanente', autoGenerated: true },
  { code: 'SCO009', libelle: 'Réintégration', categorie: 'Scolarité', moduleSource: 'scolarite', signatureRequired: true, dua: 'Permanente', autoGenerated: true },

  // 4. Examens
  { code: 'EXM001', libelle: 'Planning des examens', categorie: 'Examens', moduleSource: 'inscription', signatureRequired: false, dua: '2 ans', autoGenerated: true },
  { code: 'EXM002', libelle: 'Convocation à l\'examen', categorie: 'Examens', moduleSource: 'inscription', signatureRequired: false, dua: '1 an', autoGenerated: true },
  { code: 'EXM003', libelle: 'Liste d\'émargement', categorie: 'Examens', moduleSource: 'inscription', signatureRequired: true, dua: '5 ans', autoGenerated: true },
  { code: 'EXM004', libelle: 'Feuille de présence', categorie: 'Examens', moduleSource: 'inscription', signatureRequired: true, dua: '5 ans', autoGenerated: true },
  { code: 'EXM005', libelle: 'Liste des surveillants', categorie: 'Examens', moduleSource: 'inscription', signatureRequired: false, dua: '2 ans', autoGenerated: true },
  { code: 'EXM006', libelle: 'Sujet d\'examen', categorie: 'Examens', moduleSource: 'inscription', signatureRequired: false, dua: '2 ans', autoGenerated: false },
  { code: 'EXM007', libelle: 'Barème de correction', categorie: 'Examens', moduleSource: 'inscription', signatureRequired: false, dua: '2 ans', autoGenerated: false },
  { code: 'EXM008', libelle: 'Corrigé type', categorie: 'Examens', moduleSource: 'inscription', signatureRequired: false, dua: '2 ans', autoGenerated: false },
  { code: 'EXM009', libelle: 'Copie d\'examen', categorie: 'Examens', moduleSource: 'inscription', signatureRequired: false, dua: '1 an', autoGenerated: false },
  { code: 'EXM010', libelle: 'Rapport d\'incident', categorie: 'Examens', moduleSource: 'inscription', signatureRequired: true, dua: '5 ans', autoGenerated: false },

  // 5. Notes
  { code: 'NOT001', libelle: 'Feuille de notes', categorie: 'Notes', moduleSource: 'inscription', signatureRequired: true, dua: 'Permanente', autoGenerated: true },
  { code: 'NOT002', libelle: 'Relevé de notes', categorie: 'Notes', moduleSource: 'inscription', signatureRequired: true, dua: 'Permanente', autoGenerated: true },
  { code: 'NOT003', libelle: 'Bulletin semestriel', categorie: 'Notes', moduleSource: 'inscription', signatureRequired: true, dua: 'Permanente', autoGenerated: true },
  { code: 'NOT004', libelle: 'Bulletin annuel', categorie: 'Notes', moduleSource: 'inscription', signatureRequired: true, dua: 'Permanente', autoGenerated: true },
  { code: 'NOT005', libelle: 'Relevé provisoire', categorie: 'Notes', moduleSource: 'inscription', signatureRequired: false, dua: '2 ans', autoGenerated: true },
  { code: 'NOT006', libelle: 'Relevé définitif', categorie: 'Notes', moduleSource: 'inscription', signatureRequired: true, dua: 'Permanente', autoGenerated: true },
  { code: 'NOT007', libelle: 'Fiche de saisie des notes', categorie: 'Notes', moduleSource: 'inscription', signatureRequired: true, dua: '5 ans', autoGenerated: false },
  { code: 'NOT008', libelle: 'Bordereau de notes', categorie: 'Notes', moduleSource: 'inscription', signatureRequired: true, dua: 'Permanente', autoGenerated: true },
  { code: 'NOT009', libelle: 'Historique des notes', categorie: 'Notes', moduleSource: 'inscription', signatureRequired: false, dua: 'Permanente', autoGenerated: true },

  // 6. Délibérations
  { code: 'DEL001', libelle: 'PV de délibération', categorie: 'Délibérations', moduleSource: 'inscription', signatureRequired: true, dua: 'Permanente', autoGenerated: true },
  { code: 'DEL002', libelle: 'Liste des admis', categorie: 'Délibérations', moduleSource: 'inscription', signatureRequired: true, dua: 'Permanente', autoGenerated: true },
  { code: 'DEL003', libelle: 'Liste des ajournés', categorie: 'Délibérations', moduleSource: 'inscription', signatureRequired: true, dua: 'Permanente', autoGenerated: true },
  { code: 'DEL004', libelle: 'Liste des redoublants', categorie: 'Délibérations', moduleSource: 'inscription', signatureRequired: true, dua: 'Permanente', autoGenerated: true },
  { code: 'DEL005', libelle: 'Liste des exclus', categorie: 'Délibérations', moduleSource: 'inscription', signatureRequired: true, dua: 'Permanente', autoGenerated: true },
  { code: 'DEL006', libelle: 'Décision du jury', categorie: 'Délibérations', moduleSource: 'inscription', signatureRequired: true, dua: 'Permanente', autoGenerated: true },
  { code: 'DEL007', libelle: 'Tableau de classement', categorie: 'Délibérations', moduleSource: 'inscription', signatureRequired: false, dua: 'Permanente', autoGenerated: true },
  { code: 'DEL008', libelle: 'Tableau de validation des UE', categorie: 'Délibérations', moduleSource: 'inscription', signatureRequired: true, dua: 'Permanente', autoGenerated: true },

  // 7. Diplômes
  { code: 'DIP001', libelle: 'Diplôme', categorie: 'Diplômes', moduleSource: 'inscription', signatureRequired: true, dua: 'Permanente', autoGenerated: true },
  { code: 'DIP002', libelle: 'Attestation de réussite', categorie: 'Diplômes', moduleSource: 'inscription', signatureRequired: true, dua: 'Permanente', autoGenerated: true },
  { code: 'DIP003', libelle: 'Attestation provisoire', categorie: 'Diplômes', moduleSource: 'inscription', signatureRequired: true, dua: 'Permanente', autoGenerated: true },
  { code: 'DIP004', libelle: 'Duplicata de diplôme', categorie: 'Diplômes', moduleSource: 'inscription', signatureRequired: true, dua: 'Permanente', autoGenerated: true },
  { code: 'DIP005', libelle: 'Registre des diplômes', categorie: 'Diplômes', moduleSource: 'inscription', signatureRequired: false, dua: 'Permanente', autoGenerated: true },
  { code: 'DIP006', libelle: 'Bordereau de remise', categorie: 'Diplômes', moduleSource: 'inscription', signatureRequired: true, dua: 'Permanente', autoGenerated: true },
  { code: 'DIP007', libelle: 'Livre des diplômes', categorie: 'Diplômes', moduleSource: 'inscription', signatureRequired: false, dua: 'Permanente', autoGenerated: true },

  // 8. Pédagogie
  { code: 'PED001', libelle: 'Maquette pédagogique', categorie: 'Pédagogie', moduleSource: 'inscription', signatureRequired: false, dua: 'Permanente', autoGenerated: true },
  { code: 'PED002', libelle: 'Programme de formation', categorie: 'Pédagogie', moduleSource: 'inscription', signatureRequired: false, dua: 'Permanente', autoGenerated: true },
  { code: 'PED003', libelle: 'Plan de cours', categorie: 'Pédagogie', moduleSource: 'inscription', signatureRequired: false, dua: '5 ans', autoGenerated: true },
  { code: 'PED004', libelle: 'Fiche EC', categorie: 'Pédagogie', moduleSource: 'inscription', signatureRequired: false, dua: 'Permanente', autoGenerated: true },
  { code: 'PED005', libelle: 'Fiche UE', categorie: 'Pédagogie', moduleSource: 'inscription', signatureRequired: false, dua: 'Permanente', autoGenerated: true },
  { code: 'PED006', libelle: 'Planification des enseignements', categorie: 'Pédagogie', moduleSource: 'inscription', signatureRequired: false, dua: '5 ans', autoGenerated: true },
  { code: 'PED007', libelle: 'Cahier de texte', categorie: 'Pédagogie', moduleSource: 'inscription', signatureRequired: true, dua: '5 ans', autoGenerated: true },
  { code: 'PED008', libelle: 'Compte rendu pédagogique', categorie: 'Pédagogie', moduleSource: 'inscription', signatureRequired: true, dua: '5 ans', autoGenerated: true },

  // 9. Enseignants
  { code: 'ENS001', libelle: 'Contrat d\'enseignant', categorie: 'Enseignants', moduleSource: 'rh', signatureRequired: true, dua: 'Permanente', autoGenerated: false },
  { code: 'ENS002', libelle: 'Arrêté de nomination', categorie: 'Enseignants', moduleSource: 'rh', signatureRequired: true, dua: 'Permanente', autoGenerated: true },
  { code: 'ENS003', libelle: 'Fiche enseignant', categorie: 'Enseignants', moduleSource: 'rh', signatureRequired: false, dua: 'Permanente', autoGenerated: true },
  { code: 'ENS004', libelle: 'Charge horaire', categorie: 'Enseignants', moduleSource: 'rh', signatureRequired: true, dua: '5 ans', autoGenerated: true },
  { code: 'ENS005', libelle: 'Emploi du temps enseignant', categorie: 'Enseignants', moduleSource: 'inscription', signatureRequired: false, dua: '1 an', autoGenerated: true },
  { code: 'ENS006', libelle: 'État des heures', categorie: 'Enseignants', moduleSource: 'rh', signatureRequired: true, dua: '5 ans', autoGenerated: true },
  { code: 'ENS007', libelle: 'Bulletin de vacation', categorie: 'Enseignants', moduleSource: 'rh', signatureRequired: true, dua: '10 ans', autoGenerated: true },
  { code: 'ENS008', libelle: 'Rapport d\'activité', categorie: 'Enseignants', moduleSource: 'rh', signatureRequired: true, dua: '5 ans', autoGenerated: false },
  { code: 'ENS009', libelle: 'Évaluation des enseignants', categorie: 'Enseignants', moduleSource: 'rh', signatureRequired: false, dua: '5 ans', autoGenerated: false },

  // 10. Emplois du temps
  { code: 'EDT001', libelle: 'Emploi du temps étudiant', categorie: 'Emplois du temps', moduleSource: 'inscription', signatureRequired: false, dua: '1 an', autoGenerated: true },
  { code: 'EDT002', libelle: 'Emploi du temps enseignant', categorie: 'Emplois du temps', moduleSource: 'inscription', signatureRequired: false, dua: '1 an', autoGenerated: true },
  { code: 'EDT003', libelle: 'Occupation des salles', categorie: 'Emplois du temps', moduleSource: 'inscription', signatureRequired: false, dua: '1 an', autoGenerated: true },
  { code: 'EDT004', libelle: 'Calendrier académique', categorie: 'Emplois du temps', moduleSource: 'inscription', signatureRequired: false, dua: 'Permanente', autoGenerated: true },
  { code: 'EDT005', libelle: 'Planning des soutenances', categorie: 'Emplois du temps', moduleSource: 'inscription', signatureRequired: false, dua: '2 ans', autoGenerated: true },

  // 11. Finance
  { code: 'FIN001', libelle: 'Facture', categorie: 'Finance', moduleSource: 'comptabilite', signatureRequired: false, dua: '10 ans', autoGenerated: true },
  { code: 'FIN002', libelle: 'Reçu', categorie: 'Finance', moduleSource: 'comptabilite', signatureRequired: true, dua: '10 ans', autoGenerated: true },
  { code: 'FIN003', libelle: 'Quittance', categorie: 'Finance', moduleSource: 'comptabilite', signatureRequired: true, dua: '10 ans', autoGenerated: true },
  { code: 'FIN004', libelle: 'Bon de caisse', categorie: 'Finance', moduleSource: 'comptabilite', signatureRequired: true, dua: '10 ans', autoGenerated: true },
  { code: 'FIN005', libelle: 'Bordereau bancaire', categorie: 'Finance', moduleSource: 'comptabilite', signatureRequired: false, dua: '10 ans', autoGenerated: true },
  { code: 'FIN006', libelle: 'État des paiements', categorie: 'Finance', moduleSource: 'comptabilite', signatureRequired: false, dua: '10 ans', autoGenerated: true },
  { code: 'FIN007', libelle: 'Échéancier', categorie: 'Finance', moduleSource: 'comptabilite', signatureRequired: false, dua: '5 ans', autoGenerated: true },
  { code: 'FIN008', libelle: 'Journal de caisse', categorie: 'Finance', moduleSource: 'comptabilite', signatureRequired: false, dua: '10 ans', autoGenerated: true },
  { code: 'FIN009', libelle: 'Rapport financier', categorie: 'Finance', moduleSource: 'comptabilite', signatureRequired: true, dua: '10 ans', autoGenerated: true },

  // 12. Bibliothèque
  { code: 'BIB001', libelle: 'Carte de bibliothèque', categorie: 'Bibliothèque', moduleSource: 'scolarite', signatureRequired: false, dua: '1 an', autoGenerated: true },
  { code: 'BIB002', libelle: 'Bon d\'emprunt', categorie: 'Bibliothèque', moduleSource: 'scolarite', signatureRequired: false, dua: '2 ans', autoGenerated: true },
  { code: 'BIB003', libelle: 'Bon de retour', categorie: 'Bibliothèque', moduleSource: 'scolarite', signatureRequired: false, dua: '2 ans', autoGenerated: true },
  { code: 'BIB004', libelle: 'Inventaire bibliothèque', categorie: 'Bibliothèque', moduleSource: 'scolarite', signatureRequired: false, dua: 'Permanente', autoGenerated: true },
  { code: 'BIB005', libelle: 'Registre des ouvrages', categorie: 'Bibliothèque', moduleSource: 'scolarite', signatureRequired: false, dua: 'Permanente', autoGenerated: true },
  { code: 'BIB006', libelle: 'Rapport des prêts', categorie: 'Bibliothèque', moduleSource: 'scolarite', signatureRequired: false, dua: '5 ans', autoGenerated: true },

  // 13. Ressources humaines
  { code: 'RH001', libelle: 'Contrat de travail', categorie: 'RH', moduleSource: 'rh', signatureRequired: true, dua: 'Permanente', autoGenerated: false },
  { code: 'RH002', libelle: 'Bulletin de paie', categorie: 'RH', moduleSource: 'rh', signatureRequired: true, dua: '10 ans', autoGenerated: true },
  { code: 'RH003', libelle: 'Fiche de présence', categorie: 'RH', moduleSource: 'rh', signatureRequired: true, dua: '5 ans', autoGenerated: true },
  { code: 'RH004', libelle: 'Demande de congé', categorie: 'RH', moduleSource: 'rh', signatureRequired: false, dua: '5 ans', autoGenerated: false },
  { code: 'RH005', libelle: 'Décision de congé', categorie: 'RH', moduleSource: 'rh', signatureRequired: true, dua: 'Permanente', autoGenerated: true },
  { code: 'RH006', libelle: 'Évaluation annuelle', categorie: 'RH', moduleSource: 'rh', signatureRequired: true, dua: '5 ans', autoGenerated: false },
  { code: 'RH007', libelle: 'Dossier du personnel', categorie: 'RH', moduleSource: 'rh', signatureRequired: false, dua: 'Permanente', autoGenerated: true },

  // 14. Administration
  { code: 'ADM011', libelle: 'Courrier entrant', categorie: 'Administration', moduleSource: 'ged', signatureRequired: false, dua: '5 ans', autoGenerated: false },
  { code: 'ADM012', libelle: 'Courrier sortant', categorie: 'Administration', moduleSource: 'ged', signatureRequired: true, dua: '5 ans', autoGenerated: false },
  { code: 'ADM013', libelle: 'Note de service', categorie: 'Administration', moduleSource: 'administration', signatureRequired: true, dua: '5 ans', autoGenerated: false },
  { code: 'ADM014', libelle: 'Décision administrative', categorie: 'Administration', moduleSource: 'administration', signatureRequired: true, dua: 'Permanente', autoGenerated: false },
  { code: 'ADM015', libelle: 'Arrêté', categorie: 'Administration', moduleSource: 'administration', signatureRequired: true, dua: 'Permanente', autoGenerated: true },
  { code: 'ADM016', libelle: 'Circulaire', categorie: 'Administration', moduleSource: 'administration', signatureRequired: true, dua: '5 ans', autoGenerated: false },
  { code: 'ADM017', libelle: 'Compte rendu', categorie: 'Administration', moduleSource: 'administration', signatureRequired: true, dua: '5 ans', autoGenerated: false },
  { code: 'ADM018', libelle: 'Procès-verbal de réunion', categorie: 'Administration', moduleSource: 'administration', signatureRequired: true, dua: 'Permanente', autoGenerated: false },
  { code: 'ADM019', libelle: 'Rapport annuel', categorie: 'Administration', moduleSource: 'administration', signatureRequired: true, dua: 'Permanente', autoGenerated: false },

  // 15. Recherche
  { code: 'RCH001', libelle: 'Mémoire', categorie: 'Recherche', moduleSource: 'inscription', signatureRequired: true, dua: 'Permanente', autoGenerated: false },
  { code: 'RCH002', libelle: 'Thèse', categorie: 'Recherche', moduleSource: 'inscription', signatureRequired: true, dua: 'Permanente', autoGenerated: false },
  { code: 'RCH003', libelle: 'Rapport de stage', categorie: 'Recherche', moduleSource: 'stage', signatureRequired: true, dua: 'Permanente', autoGenerated: false },
  { code: 'RCH004', libelle: 'Convention de stage', categorie: 'Recherche', moduleSource: 'stage', signatureRequired: true, dua: 'Permanente', autoGenerated: false },
  { code: 'RCH005', libelle: 'Convention de partenariat', categorie: 'Recherche', moduleSource: 'administration', signatureRequired: true, dua: 'Permanente', autoGenerated: false },
  { code: 'RCH006', libelle: 'Rapport scientifique', categorie: 'Recherche', moduleSource: 'administration', signatureRequired: true, dua: 'Permanente', autoGenerated: false },
  { code: 'RCH007', libelle: 'Publication', categorie: 'Recherche', moduleSource: 'administration', signatureRequired: false, dua: 'Permanente', autoGenerated: false },

  // 16. Discipline
  { code: 'DSC001', libelle: 'Convocation disciplinaire', categorie: 'Discipline', moduleSource: 'scolarite', signatureRequired: false, dua: '5 ans', autoGenerated: false },
  { code: 'DSC002', libelle: 'Rapport disciplinaire', categorie: 'Discipline', moduleSource: 'scolarite', signatureRequired: true, dua: 'Permanente', autoGenerated: false },
  { code: 'DSC003', libelle: 'Avertissement', categorie: 'Discipline', moduleSource: 'scolarite', signatureRequired: true, dua: '5 ans', autoGenerated: true },
  { code: 'DSC004', libelle: 'Blâme', categorie: 'Discipline', moduleSource: 'scolarite', signatureRequired: true, dua: '5 ans', autoGenerated: true },
  { code: 'DSC005', libelle: 'Décision disciplinaire', categorie: 'Discipline', moduleSource: 'scolarite', signatureRequired: true, dua: 'Permanente', autoGenerated: true },
  { code: 'DSC006', libelle: 'Exclusion', categorie: 'Discipline', moduleSource: 'scolarite', signatureRequired: true, dua: 'Permanente', autoGenerated: true },

  // 17. Qualité
  { code: 'QLT001', libelle: 'Rapport d\'audit', categorie: 'Qualité', moduleSource: 'administration', signatureRequired: true, dua: '5 ans', autoGenerated: false },
  { code: 'QLT002', libelle: 'Rapport qualité', categorie: 'Qualité', moduleSource: 'administration', signatureRequired: true, dua: '5 ans', autoGenerated: false },
  { code: 'QLT003', libelle: 'Fiche de non-conformité', categorie: 'Qualité', moduleSource: 'administration', signatureRequired: false, dua: '5 ans', autoGenerated: false },
  { code: 'QLT004', libelle: 'Plan d\'amélioration', categorie: 'Qualité', moduleSource: 'administration', signatureRequired: true, dua: '5 ans', autoGenerated: false },

  // 18. Patrimoine
  { code: 'PAT001', libelle: 'Inventaire patrimoine', categorie: 'Patrimoine', moduleSource: 'immobilisation', signatureRequired: false, dua: 'Permanente', autoGenerated: true },
  { code: 'PAT002', libelle: 'Bon de sortie', categorie: 'Patrimoine', moduleSource: 'immobilisation', signatureRequired: true, dua: '10 ans', autoGenerated: true },
  { code: 'PAT003', libelle: 'Bon d\'entrée', categorie: 'Patrimoine', moduleSource: 'immobilisation', signatureRequired: true, dua: '10 ans', autoGenerated: true },
  { code: 'PAT004', libelle: 'Fiche matériel', categorie: 'Patrimoine', moduleSource: 'immobilisation', signatureRequired: false, dua: 'Permanente', autoGenerated: true },
  { code: 'PAT005', libelle: 'Contrat de maintenance', categorie: 'Patrimoine', moduleSource: 'immobilisation', signatureRequired: true, dua: 'Permanente', autoGenerated: false },

  // 19. Archives
  { code: 'ARC001', libelle: 'Bordereau de versement', categorie: 'Archives', moduleSource: 'ged', signatureRequired: true, dua: 'Permanente', autoGenerated: true },
  { code: 'ARC002', libelle: 'Bordereau d\'élimination', categorie: 'Archives', moduleSource: 'ged', signatureRequired: true, dua: 'Permanente', autoGenerated: true },
  { code: 'ARC003', libelle: 'Bordereau de communication', categorie: 'Archives', moduleSource: 'ged', signatureRequired: true, dua: '5 ans', autoGenerated: true },
  { code: 'ARC004', libelle: 'Inventaire d\'archives', categorie: 'Archives', moduleSource: 'ged', signatureRequired: false, dua: 'Permanente', autoGenerated: true },
  { code: 'ARC005', libelle: 'Plan de classement', categorie: 'Archives', moduleSource: 'ged', signatureRequired: false, dua: 'Permanente', autoGenerated: true },
  { code: 'ARC006', libelle: 'Calendrier de conservation (DUA)', categorie: 'Archives', moduleSource: 'ged', signatureRequired: false, dua: 'Permanente', autoGenerated: true },
  { code: 'ARC007', libelle: 'Registre des archives', categorie: 'Archives', moduleSource: 'ged', signatureRequired: false, dua: 'Permanente', autoGenerated: true },
];

export async function seedDocGenTypes(): Promise<void> {
  for (const type of DOCUMENT_TYPES) {
    const existing = await DocGenType.findOne({ where: { code: type.code } });
    if (!existing) {
      await DocGenType.create(type as any);
      console.log(`  [docgen] Type créé: ${type.code} - ${type.libelle}`);
    }
  }
  console.log(`[docgen] ${DOCUMENT_TYPES.length} types de documents synchronisés.`);
}
