export class DocGenType {
  declare id?: string
  declare code?: string
  declare libelle?: string
  declare categorie?: string
  declare moduleSource?: string
  declare description?: string
  declare signatureRequired?: boolean
  declare dua?: string
  declare autoGenerated?: boolean
  declare format?: string
  declare readonly createdAt?: Date
  declare readonly updatedAt?: Date
}
