import { Component, EventEmitter, Input, Output } from '@angular/core';

export interface Folder {
  id: number;
  nom: string;
  description?: string;
  parentId?: number | null;
  domainId?: number;
  children?: Folder[];
  isAutoGenerated?: boolean;
}

@Component({
  selector: 'app-folder-tree-item',
  template: `
    <div class="tree-item">
      <div class="tree-row" [class.selected]="selectedId === folder.id">
        <button class="tree-toggle" (click)="expanded = !expanded" *ngIf="folder.children && folder.children.length > 0">
          <svg viewBox="0 0 24 24" width="14" height="14" fill="none" stroke="currentColor" stroke-width="2" [class.rotated]="expanded"><polyline points="9 18 15 12 9 6"/></svg>
        </button>
        <span class="tree-spacer" *ngIf="!folder.children || folder.children.length === 0"></span>
        <button class="tree-label" (click)="$event.stopPropagation(); select.emit(folder)">
          <svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M22 19a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5l2 3h9a2 2 0 0 1 2 2z"/></svg>
          {{ folder.nom }}
        </button>
        <button class="tree-delete" title="Supprimer" (click)="$event.stopPropagation(); delete.emit(folder.id)">
          <svg viewBox="0 0 24 24" width="14" height="14" fill="none" stroke="currentColor" stroke-width="2"><polyline points="3 6 5 6 21 6"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/></svg>
        </button>
      </div>
      <div class="tree-children" *ngIf="expanded && folder.children && folder.children.length > 0">
        <app-folder-tree-item
          *ngFor="let child of folder.children"
          [folder]="child"
          [selectedId]="selectedId"
          (select)="select.emit($event)"
          (delete)="delete.emit($event)">
        </app-folder-tree-item>
      </div>
    </div>
  `,
  styles: [`
    .tree-item {
      display: flex;
      flex-direction: column;
    }
    .tree-row {
      display: flex;
      align-items: center;
      gap: 4px;
      padding: 6px 8px;
      border-radius: 8px;
      cursor: pointer;
      transition: background 0.15s;
      &:hover {
        background: #f1f5f9;
      }
      &.selected {
        background: #eef2ff;
        .tree-label {
          color: #3b5bff;
          font-weight: 600;
        }
      }
    }
    .tree-toggle {
      display: inline-flex;
      align-items: center;
      justify-content: center;
      width: 20px;
      height: 20px;
      border: none;
      background: transparent;
      cursor: pointer;
      color: #64748b;
      svg.rotated {
        transform: rotate(90deg);
      }
    }
    .tree-spacer {
      width: 20px;
      flex-shrink: 0;
    }
    .tree-label {
      display: inline-flex;
      align-items: center;
      gap: 6px;
      flex: 1;
      font-size: 13px;
      color: #1e293b;
      background: transparent;
      border: none;
      cursor: pointer;
      padding: 2px 4px;
      border-radius: 4px;
      text-align: left;
      white-space: nowrap;
      overflow: hidden;
      text-overflow: ellipsis;
    }
    .tree-delete {
      display: inline-flex;
      align-items: center;
      justify-content: center;
      width: 24px;
      height: 24px;
      border: none;
      background: transparent;
      cursor: pointer;
      color: #94a3b8;
      border-radius: 4px;
      opacity: 0;
      transition: all 0.15s;
      &:hover {
        background: #fef2f2;
        color: #dc2626;
      }
    }
    .tree-row:hover .tree-delete {
      opacity: 1;
    }
    .tree-children {
      margin-left: 18px;
      border-left: 1px solid #e2e8f0;
      padding-left: 4px;
      display: flex;
      flex-direction: column;
      gap: 2px;
    }
  `]
})
export class FolderTreeItemComponent {
  @Input() folder!: Folder;
  @Input() selectedId: number = 0;
  @Output() select = new EventEmitter<Folder>();
  @Output() delete = new EventEmitter<number>();

  expanded = false;
}
