import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { GedService, GedDocument, ProcessusGenerateur } from 'src/app/data/modules/ged/services/ged.service';

interface Folder {
  id: number;
  nom: string;
  description?: string;
  parentId?: number | null;
  domainId?: number;
  children?: Folder[];
  isAutoGenerated?: boolean;
}

@Component({
  selector: 'app-ged-merge',
  templateUrl: './ged-merge.component.html',
  styleUrls: ['./ged-merge.component.scss']
})
export class GedMergeComponent implements OnInit {
  // ── Folder tree ──
  allFolders: Folder[] = [];
  selectedFolder: Folder | null = null;
  currentPath: Folder[] = [];
  documents: GedDocument[] = [];
  loading = false;
  newFolderName = '';
  showCreateInput = false;

  // ── Upload ──
  selectedFiles: File[] = [];
  showUploadForm = false;
  uploading = false;
  uploadProgress = 0;

  titre = '';
  reference = '';
  categorie = '';
  dureeConservation = '';
  archivedUntil?: string;
  isArchived = false;
  sessions: any[] = [];
  selectedSessionId?: number;
  processusGenerateurs: ProcessusGenerateur[] = [];
  selectedProcessusGenerateurId?: string;
  storageLocation = 'local';
  isEncrypted = false;
  sourceType = 'numerise_interne';
  externalIssuer = '';
  destinataire = '';
  dateDocument = '';
  receptionDate = '';
  dateEnvoi = '';
  modeEnvoi = '';



  // ── Upload folder target ──
  showCreateSubfolder = false;
  showCreateRoot = false;
  showFolderPicker = false;

  // ── Nomenclature ──
  nomenclaturePrefix = '';
  nomenclatureCategorie = '';
  nomenclatureReference = '';
  nomenclatureResult = '';

  // ── Quick session ──
  showNewSession = false;
  newSessionNom = '';
  newSessionDescription = '';

  constructor(
    private gedService: GedService,
    private router: Router
  ) {}

  ngOnInit(): void {
    this.loadFolders();
    this.gedService.getSessions().subscribe({ next: s => this.sessions = s });
    this.gedService.getProcessusGenerateurs().subscribe({ next: p => this.processusGenerateurs = p });
  }

  // ── Folder tree ──

  loadFolders() {
    this.loading = true;
    this.gedService.getFolders().subscribe({
      next: (folders) => {
        this.buildChildren(folders);
        this.loading = false;
      },
      error: () => this.loading = false
    });
  }

  private buildChildren(folders: Folder[]) {
    const map = new Map<number, Folder>();
    for (const f of folders) map.set(f.id, { ...f, children: [] });
    const roots: Folder[] = [];
    for (const f of folders) {
      const node = map.get(f.id)!;
      if (f.parentId && map.has(f.parentId)) map.get(f.parentId)!.children!.push(node);
      else roots.push(node);
    }
    this.allFolders = roots;
  }

  selectFolder(folder: Folder) {
    this.selectedFolder = folder;
    this.currentPath = this.buildPath(folder);
    this.loadDocuments(folder.id);
    this.showUploadForm = false;
  }

  private buildPath(target: Folder): Folder[] {
    const path: Folder[] = [target];
    let current = target;
    while (current.parentId) {
      const parent = this.findNode(this.allFolders, current.parentId);
      if (parent) { path.unshift(parent); current = parent; }
      else break;
    }
    return path;
  }

  private findNode(folders: Folder[], id: number): Folder | null {
    for (const f of folders) {
      if (f.id === id) return f;
      if (f.children) { const found = this.findNode(f.children, id); if (found) return found; }
    }
    return null;
  }

  goToRoot() {
    this.selectedFolder = null;
    this.currentPath = [];
    this.documents = [];
    this.showUploadForm = false;
  }

  get subFolders(): Folder[] {
    return this.selectedFolder?.children || [];
  }

  createFolder() {
    if (!this.newFolderName.trim()) return;
    const payload: any = { nom: this.newFolderName.trim() };
    if (this.selectedFolder) payload.parentId = this.selectedFolder.id;
    this.gedService.createFolder(payload).subscribe({
      next: () => { this.newFolderName = ''; this.showCreateInput = false; this.loadFolders(); },
      error: e => alert('Erreur: ' + (e.error?.message || e.statusText))
    });
  }

  deleteFolder(id: number) {
    if (!confirm('Supprimer ce dossier ?')) return;
    this.gedService.deleteFolder(String(id)).subscribe({
      next: () => { this.loadFolders(); if (this.selectedFolder?.id === id) this.goToRoot(); },
      error: e => alert('Erreur: ' + (e.error?.message || e.statusText))
    });
  }

  private loadDocuments(folderId: number) {
    this.gedService.getAll({ folderId }).subscribe({
      next: (docs: any) => { this.documents = Array.isArray(docs) ? docs : docs?.data || []; }
    });
  }

  // ── Upload ──

  toggleUpload() {
    this.showUploadForm = !this.showUploadForm;
    if (!this.showUploadForm) this.resetForm();
    this.showCreateSubfolder = false;
    this.showCreateRoot = false;
    this.showFolderPicker = false;
  }

  selectFolderInUpload() {
    this.showFolderPicker = !this.showFolderPicker;
    this.showCreateSubfolder = false;
    this.showCreateRoot = false;
  }

  pickFolder(folder: Folder) {
    this.selectFolder(folder);
    this.showFolderPicker = false;
  }

  createFolderInline() {
    if (!this.newFolderName.trim()) return;
    const payload: any = { nom: this.newFolderName.trim() };
    if (this.selectedFolder) payload.parentId = this.selectedFolder.id;
    this.gedService.createFolder(payload).subscribe({
      next: (created: any) => {
        const folderId = created?.id || created?.data?.id;
        this.newFolderName = '';
        this.showCreateSubfolder = false;
        this.showCreateRoot = false;
        this.loadFolders();
        if (folderId) {
          this.selectFolder({ id: folderId, nom: payload.nom } as Folder);
        }
      },
      error: e => alert('Erreur: ' + (e.error?.message || e.statusText))
    });
  }

  onFileSelected(event: Event) {
    const files = (event.target as HTMLInputElement).files;
    if (files) this.addFiles(Array.from(files));
  }

  onFileDropped(event: DragEvent) {
    event.preventDefault();
    const files = event.dataTransfer?.files;
    if (files) this.addFiles(Array.from(files));
  }

  private addFiles(files: File[]) {
    const pdfs = files.filter(f => f.type === 'application/pdf');
    if (pdfs.length !== files.length) alert('Seuls les fichiers PDF sont acceptés — les fichiers non-PDF ont été ignorés');
    if (pdfs.length === 0) return;
    this.selectedFiles.push(...pdfs);
    this.showUploadForm = true;
  }

  removeFile(index: number) {
    this.selectedFiles.splice(index, 1);
    if (this.selectedFiles.length === 0) this.resetForm();
  }

  resetForm() {
    this.selectedFiles = [];
    this.titre = '';
    this.reference = '';
    this.categorie = '';
    this.dureeConservation = '';
    this.archivedUntil = undefined;
    this.isArchived = false;
    this.selectedSessionId = undefined;
    this.selectedProcessusGenerateurId = undefined;
    this.storageLocation = 'local';
    this.isEncrypted = false;
    this.sourceType = 'numerise_interne';
    this.externalIssuer = '';
    this.destinataire = '';
    this.dateDocument = '';
    this.receptionDate = '';
    this.dateEnvoi = '';
    this.modeEnvoi = '';
  }

  upload() {
    if (this.selectedFiles.length === 0) return;
    this.uploading = true;
    this.uploadProgress = 0;

    const metadata: Record<string, any> = {
      anneeAcademiqueId: undefined,
      domainId: undefined,
      documentTypeId: undefined,
      confidentialityLevel: this.sourceType === 'numerise_interne' ? 'interne' : 'public',
      sourceType: this.sourceType,
      dateDocument: this.dateDocument || undefined,
      folderId: this.selectedFolder && this.selectedFolder.id > 0 ? String(this.selectedFolder.id) : undefined,
      sessionId: this.selectedSessionId,
      processusGenerateurId: this.selectedProcessusGenerateurId,
      storageLocation: this.storageLocation,
      isEncrypted: this.isEncrypted,
      externalIssuer: this.externalIssuer || undefined,
    };

    this.gedService.batchUploadEnhanced(this.selectedFiles, metadata).subscribe({
      next: (res: any) => {
        this.resetForm();
        this.showUploadForm = false;
        this.uploading = false;
        if (this.selectedFolder) this.loadDocuments(this.selectedFolder.id);
      },
      error: (e) => {
        alert('Erreur: ' + (e.error?.message || e.statusText));
        this.uploading = false;
      }
    });
  }

  // ── Nomenclature ──

  generateNomenclature() {
    const parts = [this.nomenclaturePrefix || 'GED', new Date().toISOString().slice(0, 10).replace(/-/g, ''), this.nomenclatureCategorie || 'DOC', this.nomenclatureReference || 'REF'];
    this.nomenclatureResult = parts.join('_').toUpperCase();
  }

  // ── Session ──

  toggleNewSession() { this.showNewSession = !this.showNewSession; }

  createQuickSession() {
    if (!this.newSessionNom) return;
    this.gedService.createSession({ nom: this.newSessionNom, description: this.newSessionDescription }).subscribe({
      next: (s: any) => {
        this.sessions.unshift(s);
        this.selectedSessionId = s.id;
        this.showNewSession = false;
        this.newSessionNom = '';
        this.newSessionDescription = '';
      },
      error: (e) => alert('Erreur: ' + (e.error?.message || e.statusText))
    });
  }

  selectSession(session: any) {
    this.selectedSessionId = session.id;
    this.showUploadForm = true;
  }

  // ── Navigation ──

  navigateToDocument(doc: GedDocument) {
    this.router.navigate(['/ged/document', doc.id]);
  }

  downloadDoc(doc: GedDocument) {
    window.open(this.gedService.getDownloadUrl(doc.id), '_blank');
  }

  formatSize(bytes: number): string {
    if (bytes > 1048576) return (bytes / 1048576).toFixed(1) + ' Mo';
    if (bytes > 1024) return (bytes / 1024).toFixed(1) + ' Ko';
    return bytes + ' o';
  }
}
