import { Model, InferAttributes, InferCreationAttributes, CreationOptional, DataTypes, ForeignKey } from "sequelize";
import { DatabaseConnection } from "../../../core/helpers/DatabaseConnection";
import { MODULE_MODEL_PREFIX, MODULE_TABLE_PREFIX } from "../GedModule";
import { Utilisateur } from "../../auth/models/Utilisateur";
import Domain from "./Domain";

export class Folder extends Model<InferAttributes<Folder>, InferCreationAttributes<Folder>> {
  declare id: CreationOptional<number>
  declare nom: string
  declare description: CreationOptional<string>
  declare parentId: CreationOptional<number>
  declare domainId: CreationOptional<number>
  declare createdBy: ForeignKey<Utilisateur['id']>
  declare isAutoGenerated: CreationOptional<boolean>
  declare folderType: CreationOptional<string>
  declare anneeAcademiqueId: CreationOptional<number>

  declare readonly createdAt: CreationOptional<Date>
  declare readonly updatedAt: CreationOptional<Date>
}

Folder.init({
  id: {
    type: DataTypes.INTEGER.UNSIGNED,
    autoIncrement: true,
    primaryKey: true
  },
  nom: {
    type: new DataTypes.STRING,
    allowNull: false
  },
  description: {
    type: DataTypes.TEXT,
    allowNull: true
  },
  parentId: {
    type: DataTypes.INTEGER.UNSIGNED,
    allowNull: true
  },
  domainId: {
    type: DataTypes.INTEGER.UNSIGNED,
    allowNull: true
  },
  createdBy: {
    type: DataTypes.INTEGER.UNSIGNED,
    allowNull: false
  },
  isAutoGenerated: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: false },
  folderType: { type: DataTypes.STRING(30), allowNull: true },
  anneeAcademiqueId: { type: DataTypes.INTEGER.UNSIGNED, allowNull: true },
  createdAt: DataTypes.DATE,
  updatedAt: DataTypes.DATE
}, {
  sequelize: DatabaseConnection.getInstance().sequelize,
  paranoid: true,
  modelName: MODULE_MODEL_PREFIX + 'Folder',
  tableName: MODULE_TABLE_PREFIX + 'folders',
  timestamps: true
});

export default Folder;
