-- Add tracking fields to ged_documents
ALTER TABLE ged_documents 
  ADD COLUMN destinataire VARCHAR(255) NULL AFTER dateDocument,
  ADD COLUMN dateEnvoi DATE NULL AFTER destinataire,
  ADD COLUMN modeEnvoi ENUM('courrier', 'email', 'remise_main_propre', 'fax') NULL AFTER dateEnvoi,
  ADD COLUMN accuseReception BOOLEAN NOT NULL DEFAULT FALSE AFTER modeEnvoi,
  ADD COLUMN numeroCourrier VARCHAR(50) NULL AFTER accuseReception;

-- Alter sourceType ENUM to add document_sortant
ALTER TABLE ged_documents 
  MODIFY COLUMN sourceType ENUM('genere_application', 'numerise_interne', 'recu_externe', 'document_sortant') NOT NULL DEFAULT 'numerise_interne';

-- Add isAutoGenerated to ged_folders
ALTER TABLE ged_folders 
  ADD COLUMN isAutoGenerated BOOLEAN NOT NULL DEFAULT FALSE AFTER createdBy;
