import { Op, literal } from "sequelize";
import { DatabaseConnection } from "../../../core/helpers/DatabaseConnection";
import Domain from "../models/Domain";
import Folder from "../models/Folder";
import { ProcessusGenerateur } from "../models/ProcessusGenerateur";

const AnneeAcademique = () => DatabaseConnection.getInstance().sequelize.model('InsAnneeAcademique') as any;
const NiveauEtude = () => DatabaseConnection.getInstance().sequelize.model('InsNiveauEtude') as any;
const Parcours = () => DatabaseConnection.getInstance().sequelize.model('InsParcours') as any;
const Classe = () => DatabaseConnection.getInstance().sequelize.model('InsClasse') as any;
const RhDepartement = () => DatabaseConnection.getInstance().sequelize.model('RhDepartement') as any;
const RhEmploye = () => DatabaseConnection.getInstance().sequelize.model('RhEmploye') as any;
const Fournisseur = () => DatabaseConnection.getInstance().sequelize.model('AchatsFournisseur') as any;
const Apprenant = () => DatabaseConnection.getInstance().sequelize.model('InsApprenant') as any;

const TYPES = {
  YEAR: 'YEAR',
  DOMAIN: 'DOMAIN',
  PROCESS: 'PROCESS',
  NIVEAU: 'NIVEAU',
  CLASSE: 'CLASSE',
  SERVICE: 'SERVICE',
  EMPLOYE: 'EMPLOYE',
  FOURNISSEUR: 'FOURNISSEUR',
  INSTANCE: 'INSTANCE',
  PARTENAIRE: 'PARTENAIRE',
  LABORATOIRE: 'LABORATOIRE',
  SITE: 'SITE',
  MATRICULE: 'MATRICULE',
  PARCOURS: 'PARCOURS',
  CONVENTION: 'CONVENTION',
  DOSSIER_ETUDIANT: 'DOSSIER_ETUDIANT'
};

export class FolderAutoService {
  static async generateForAcademicYear(anneeAcademiqueId: number, utilisateurId: number): Promise<void> {
    const annee = await AnneeAcademique().findByPk(anneeAcademiqueId);
    if (!annee) return;
    const anneeLabel = annee.libelle || `Année ${anneeAcademiqueId}`;
    const anneeCode = annee.code_annee || anneeLabel.replace('/', '-') || String(anneeAcademiqueId);

    const yearFolder = await Folder.findOrCreate({
      where: { folderType: TYPES.YEAR, anneeAcademiqueId, parentId: { [Op.is]: null } as any },
      defaults: { nom: anneeLabel, folderType: TYPES.YEAR, anneeAcademiqueId, createdBy: utilisateurId, isAutoGenerated: true }
    } as any);

    const domains = await Domain.findAll();
    const processus = await ProcessusGenerateur.findAll({ where: { isActif: true } });

    for (const domain of domains) {
      const domainFolder = await Folder.findOrCreate({
        where: { folderType: TYPES.DOMAIN, domainId: domain.id, parentId: yearFolder[0].id, anneeAcademiqueId },
        defaults: { nom: domain.label, folderType: TYPES.DOMAIN, domainId: domain.id, parentId: yearFolder[0].id, anneeAcademiqueId, createdBy: utilisateurId, isAutoGenerated: true }
      } as any);

      if (domain.code === 'SCOL') {
        await this.generateScolTree(domainFolder[0], domain, processus, anneeAcademiqueId, utilisateurId);
      } else if (domain.code === 'RH') {
        await this.generateRhTree(domainFolder[0], domain, processus, anneeAcademiqueId, utilisateurId);
      } else if (domain.code === 'FIN') {
        await this.generateFinTree(domainFolder[0], domain, processus, anneeAcademiqueId, utilisateurId);
      } else if (domain.code === 'REC') {
        await this.generateRecTree(domainFolder[0], domain, processus, anneeAcademiqueId, utilisateurId);
      } else if (domain.code === 'GOUV') {
        await this.generateGouvTree(domainFolder[0], domain, processus, anneeAcademiqueId, utilisateurId);
      } else if (domain.code === 'PAT') {
        await this.generatePatTree(domainFolder[0], domain, processus, anneeAcademiqueId, utilisateurId);
      } else if (domain.code === 'EXT') {
        await this.generateExtTree(domainFolder[0], domain, processus, anneeAcademiqueId, utilisateurId);
      } else {
        for (const proc of processus) {
          await Folder.findOrCreate({
            where: { folderType: TYPES.PROCESS, nom: proc.libelle, parentId: domainFolder[0].id, anneeAcademiqueId },
            defaults: { nom: proc.libelle, folderType: TYPES.PROCESS, parentId: domainFolder[0].id, domainId: domain.id, anneeAcademiqueId, createdBy: utilisateurId, isAutoGenerated: true }
          } as any);
        }
      }
    }
  }

  static async generateForYears(anneeIds: number[], utilisateurId: number): Promise<string[]> {
    const generated: string[] = [];
    for (const anneeId of anneeIds) {
      const exists = await Folder.findOne({ where: { folderType: TYPES.YEAR, anneeAcademiqueId: anneeId } });
      if (exists) continue;
      await this.generateForAcademicYear(anneeId, utilisateurId);
      generated.push(String(anneeId));
    }
    return generated;
  }

  // ── SCOL : Année → SCOL → Process → Niveau → Parcours → Classe ──
  private static async generateScolTree(parent: Folder, domain: Domain, processus: any[], anneeId: number, userId: number) {
    for (const proc of processus) {
      const procFolder = await Folder.findOrCreate({
        where: { folderType: TYPES.PROCESS, nom: proc.libelle, parentId: parent.id, anneeAcademiqueId: anneeId },
        defaults: { nom: proc.libelle, folderType: TYPES.PROCESS, parentId: parent.id, domainId: domain.id, anneeAcademiqueId: anneeId, createdBy: userId, isAutoGenerated: true }
      } as any);

      const niveaux = await NiveauEtude().findAll({ order: [['libelle', 'ASC']] }) || [];
      for (const niveau of niveaux) {
        const nivFolder = await Folder.findOrCreate({
          where: { folderType: TYPES.NIVEAU, nom: niveau.libelle, parentId: procFolder[0].id, anneeAcademiqueId: anneeId },
          defaults: { nom: niveau.libelle, folderType: TYPES.NIVEAU, parentId: procFolder[0].id, domainId: domain.id, anneeAcademiqueId: anneeId, createdBy: userId, isAutoGenerated: true }
        } as any);

        const parcours = await Parcours().findAll({ where: { niveauEtudeId: niveau.id }, order: [['titre', 'ASC']] }) || [];
        for (const parc of parcours) {
          const parcFolder = await Folder.findOrCreate({
            where: { folderType: TYPES.PARCOURS, nom: parc.titre, parentId: nivFolder[0].id, anneeAcademiqueId: anneeId },
            defaults: { nom: parc.titre, folderType: TYPES.PARCOURS, parentId: nivFolder[0].id, domainId: domain.id, anneeAcademiqueId: anneeId, createdBy: userId, isAutoGenerated: true }
          } as any);

          const classes = await Classe().findAll({ where: { niveauEtudeId: niveau.id }, order: [['libelle', 'ASC']] }) || [];
          for (const cls of classes) {
            await Folder.findOrCreate({
              where: { folderType: TYPES.CLASSE, nom: cls.libelle, parentId: parcFolder[0].id, anneeAcademiqueId: anneeId },
              defaults: { nom: cls.libelle, folderType: TYPES.CLASSE, parentId: parcFolder[0].id, domainId: domain.id, anneeAcademiqueId: anneeId, createdBy: userId, isAutoGenerated: true }
            } as any);
          }
        }
      }
    }
  }

  // ── RH : Année → RH → Process → Service → Employé ──
  private static async generateRhTree(parent: Folder, domain: Domain, processus: any[], anneeId: number, userId: number) {
    for (const proc of processus) {
      const procFolder = await Folder.findOrCreate({
        where: { folderType: TYPES.PROCESS, nom: proc.libelle, parentId: parent.id, anneeAcademiqueId: anneeId },
        defaults: { nom: proc.libelle, folderType: TYPES.PROCESS, parentId: parent.id, domainId: domain.id, anneeAcademiqueId: anneeId, createdBy: userId, isAutoGenerated: true }
      } as any);

      const depts = await RhDepartement().findAll({ order: [['nom', 'ASC']] }) || [];
      for (const dept of depts) {
        const deptFolder = await Folder.findOrCreate({
          where: { folderType: TYPES.SERVICE, nom: dept.nom, parentId: procFolder[0].id, anneeAcademiqueId: anneeId },
          defaults: { nom: dept.nom, folderType: TYPES.SERVICE, parentId: procFolder[0].id, domainId: domain.id, anneeAcademiqueId: anneeId, createdBy: userId, isAutoGenerated: true }
        } as any);

        const employes = await RhEmploye().findAll({ where: { departementId: dept.id }, order: [['nom', 'ASC']] }) || [];
        for (const emp of employes) {
          const matricule = emp.matricule || `E${String(emp.id).padStart(5, '0')}`;
          await Folder.findOrCreate({
            where: { folderType: TYPES.EMPLOYE, nom: `${emp.nom} ${emp.prenom || ''} (${matricule})`.trim(), parentId: deptFolder[0].id, anneeAcademiqueId: anneeId },
            defaults: { nom: `${emp.nom} ${emp.prenom || ''} (${matricule})`.trim(), folderType: TYPES.EMPLOYE, parentId: deptFolder[0].id, domainId: domain.id, anneeAcademiqueId: anneeId, createdBy: userId, isAutoGenerated: true }
          } as any);
        }
      }
    }
  }

  // ── FIN : Année → FIN → Process → Fournisseur ──
  private static async generateFinTree(parent: Folder, domain: Domain, processus: any[], anneeId: number, userId: number) {
    for (const proc of processus) {
      const procFolder = await Folder.findOrCreate({
        where: { folderType: TYPES.PROCESS, nom: proc.libelle, parentId: parent.id, anneeAcademiqueId: anneeId },
        defaults: { nom: proc.libelle, folderType: TYPES.PROCESS, parentId: parent.id, domainId: domain.id, anneeAcademiqueId: anneeId, createdBy: userId, isAutoGenerated: true }
      } as any);

      const fournisseurs = await Fournisseur().findAll({ order: [['nom', 'ASC']] }) || [];
      for (const four of fournisseurs) {
        await Folder.findOrCreate({
          where: { folderType: TYPES.FOURNISSEUR, nom: four.nom, parentId: procFolder[0].id, anneeAcademiqueId: anneeId },
          defaults: { nom: four.nom, folderType: TYPES.FOURNISSEUR, parentId: procFolder[0].id, domainId: domain.id, anneeAcademiqueId: anneeId, createdBy: userId, isAutoGenerated: true }
        } as any);
      }
    }
  }

  // ── REC : Année → REC → Process ──
  private static async generateRecTree(parent: Folder, domain: Domain, processus: any[], anneeId: number, userId: number) {
    for (const proc of processus) {
      await Folder.findOrCreate({
        where: { folderType: TYPES.PROCESS, nom: proc.libelle, parentId: parent.id, anneeAcademiqueId: anneeId },
        defaults: { nom: proc.libelle, folderType: TYPES.PROCESS, parentId: parent.id, domainId: domain.id, anneeAcademiqueId: anneeId, createdBy: userId, isAutoGenerated: true }
      } as any);
    }
  }

  // ── GOUV : Année → GOUV → Process → Instance ──
  private static async generateGouvTree(parent: Folder, domain: Domain, processus: any[], anneeId: number, userId: number) {
    const instances = ['Conseil d\'Administration', 'Conseil Académique', 'Comité de Gestion'];
    for (const proc of processus) {
      const procFolder = await Folder.findOrCreate({
        where: { folderType: TYPES.PROCESS, nom: proc.libelle, parentId: parent.id, anneeAcademiqueId: anneeId },
        defaults: { nom: proc.libelle, folderType: TYPES.PROCESS, parentId: parent.id, domainId: domain.id, anneeAcademiqueId: anneeId, createdBy: userId, isAutoGenerated: true }
      } as any);

      for (const instance of instances) {
        await Folder.findOrCreate({
          where: { folderType: TYPES.INSTANCE, nom: instance, parentId: procFolder[0].id, anneeAcademiqueId: anneeId },
          defaults: { nom: instance, folderType: TYPES.INSTANCE, parentId: procFolder[0].id, domainId: domain.id, anneeAcademiqueId: anneeId, createdBy: userId, isAutoGenerated: true }
        } as any);
      }
    }
  }

  // ── PAT : Année → PAT → Process → Site ──
  private static async generatePatTree(parent: Folder, domain: Domain, processus: any[], anneeId: number, userId: number) {
    const sites = ['Campus Principal', 'Campus Annexe', 'Résidence'];
    for (const proc of processus) {
      const procFolder = await Folder.findOrCreate({
        where: { folderType: TYPES.PROCESS, nom: proc.libelle, parentId: parent.id, anneeAcademiqueId: anneeId },
        defaults: { nom: proc.libelle, folderType: TYPES.PROCESS, parentId: parent.id, domainId: domain.id, anneeAcademiqueId: anneeId, createdBy: userId, isAutoGenerated: true }
      } as any);

      for (const site of sites) {
        await Folder.findOrCreate({
          where: { folderType: TYPES.SITE, nom: site, parentId: procFolder[0].id, anneeAcademiqueId: anneeId },
          defaults: { nom: site, folderType: TYPES.SITE, parentId: procFolder[0].id, domainId: domain.id, anneeAcademiqueId: anneeId, createdBy: userId, isAutoGenerated: true }
        } as any);
      }
    }
  }

  // ── Création du dossier MATRICULE sous la classe GED ──
  static async creerDossierMatricule(params: {
    anneeAcademiqueId: number;
    parcoursNom: string;
    classeNom: string;
    niveauNom: string;
    matricule: string;
    utilisateurId: number;
  }): Promise<void> {
    const { anneeAcademiqueId, parcoursNom, classeNom, niveauNom, matricule, utilisateurId } = params;

    const domain = await Domain.findOne({ where: { code: 'SCOL' } });
    if (!domain) return;

    // Remonter la hiérarchie : Année → SCOL → Inscription → Niveau → Parcours → Classe
    const anneeFolder = await Folder.findOne({
      where: { folderType: TYPES.YEAR, anneeAcademiqueId, parentId: { [Op.is]: null } as any }
    });
    if (!anneeFolder) return;

    const scolFolder = await Folder.findOne({
      where: { folderType: TYPES.DOMAIN, domainId: domain.id, parentId: anneeFolder.id, anneeAcademiqueId }
    });
    if (!scolFolder) return;

    // Chercher le process "Inscription"
    const processFolder = await Folder.findOne({
      where: { folderType: TYPES.PROCESS, parentId: scolFolder.id, anneeAcademiqueId }
    });
    if (!processFolder) return;

    // Niveau
    const nivFolder = await Folder.findOne({
      where: { folderType: TYPES.NIVEAU, nom: niveauNom, parentId: processFolder.id, anneeAcademiqueId }
    });
    if (!nivFolder) return;

    // Parcours
    const parcFolder = await Folder.findOne({
      where: { folderType: TYPES.PARCOURS, nom: parcoursNom, parentId: nivFolder.id, anneeAcademiqueId }
    });
    if (!parcFolder) return;

    // Classe
    const classeFolder = await Folder.findOne({
      where: { folderType: TYPES.CLASSE, nom: classeNom, parentId: parcFolder.id, anneeAcademiqueId }
    });
    if (!classeFolder) return;

    // Créer le dossier MATRICULE sous la classe
    const matriculeFolder = await Folder.findOrCreate({
      where: { folderType: TYPES.MATRICULE, nom: matricule, parentId: classeFolder.id, anneeAcademiqueId },
      defaults: {
        nom: matricule,
        folderType: TYPES.MATRICULE,
        parentId: classeFolder.id,
        domainId: domain.id,
        anneeAcademiqueId,
        createdBy: utilisateurId,
        isAutoGenerated: true
      }
    } as any);

    // Créer les sous-dossiers du matricule
    const sousDossiers = [
      'Autorisations', 'Bordereaux', 'Bulletins', 'Cartes',
      'Diplomes', 'Dossiers', 'Paiements', 'PV'
    ];
    for (const nom of sousDossiers) {
      await Folder.findOrCreate({
        where: { folderType: TYPES.DOSSIER_ETUDIANT, nom, parentId: matriculeFolder[0].id, anneeAcademiqueId },
        defaults: {
          nom,
          folderType: TYPES.DOSSIER_ETUDIANT,
          parentId: matriculeFolder[0].id,
          domainId: domain.id,
          anneeAcademiqueId,
          createdBy: utilisateurId,
          isAutoGenerated: true
        }
      } as any);
    }
  }

  // ── EXT : Année → EXT → Process → Partenaire ──
  private static async generateExtTree(parent: Folder, domain: Domain, processus: any[], anneeId: number, userId: number) {
    for (const proc of processus) {
      const procFolder = await Folder.findOrCreate({
        where: { folderType: TYPES.PROCESS, nom: proc.libelle, parentId: parent.id, anneeAcademiqueId: anneeId },
        defaults: { nom: proc.libelle, folderType: TYPES.PROCESS, parentId: parent.id, domainId: domain.id, anneeAcademiqueId: anneeId, createdBy: userId, isAutoGenerated: true }
      } as any);

      await Folder.findOrCreate({
        where: { folderType: TYPES.PARTENAIRE, nom: 'Partenaires', parentId: procFolder[0].id, anneeAcademiqueId: anneeId },
        defaults: { nom: 'Partenaires', folderType: TYPES.PARTENAIRE, parentId: procFolder[0].id, domainId: domain.id, anneeAcademiqueId: anneeId, createdBy: userId, isAutoGenerated: true }
      } as any);
    }
  }
}
