import { Op } from "sequelize";
import { DatabaseConnection } from "../../../core/helpers/DatabaseConnection";
import { DocumentGed } from "../models/DocumentGed";
import { ProcessusGenerateur } from "../models/ProcessusGenerateur";
import Domain from "../models/Domain";
import DocumentType from "../models/DocumentType";
import Folder from "../models/Folder";
import { AuditService } from "../../../core/services/AuditService";
import * as path from "path";
import * as fs from "fs";

export interface GedDocumentInput {
  titre: string;
  fichier: string;
  taille?: string;
  domaineCode: string;
  processusCode?: string;
  documentTypeCode?: string;
  sourceType?: string;

  anneeAcademiqueId?: number;
  niveauEtudeId?: number;
  parcoursId?: number;
  classeId?: number;
  semestre?: string;

  employeId?: number;
  departementId?: number;

  fournisseurId?: number;

  externalIssuer?: string;
  destinataire?: string;
  dateDocument?: Date;
  receptionDate?: Date;
  dateEnvoi?: Date;
  modeEnvoi?: string;

  metadata?: Record<string, any>;
}

export class GedIntegrationService {

  static async createDocument(input: GedDocumentInput, userId: number): Promise<DocumentGed> {
    const domaine = await Domain.findOne({ where: { code: input.domaineCode } });
    if (!domaine) throw new Error(`Domaine ${input.domaineCode} non trouvé`);

    let processus: ProcessusGenerateur | null = null;
    if (input.processusCode) {
      processus = await ProcessusGenerateur.findOne({ where: { code: input.processusCode } });
    }

    let documentType: DocumentType | null = null;
    if (input.documentTypeCode) {
      documentType = await DocumentType.findOne({ where: { code: input.documentTypeCode } });
    }

    const folderId = await this.resolveFolderId(domaine.id, input, userId);

    const doc = await DocumentGed.create({
      titre: input.titre,
      reference: await this.generateReference(domaine.code),
      fichier: input.fichier,
      taille: input.taille || null,
      domainId: domaine.id,
      documentTypeId: documentType?.id || null,
      processusGenerateurId: processus?.id || null,
      sourceType: input.sourceType || 'genere_application',
      confidentialityLevel: documentType?.defaultConfidentiality || 'interne',
      lifecycleStatus: 'courant',
      externalIssuer: input.externalIssuer || null,
      destinataire: input.destinataire || null,
      dateDocument: input.dateDocument || null,
      receptionDate: input.receptionDate || null,
      dateEnvoi: input.dateEnvoi || null,
      modeEnvoi: input.modeEnvoi || null,
      anneeAcademiqueId: input.anneeAcademiqueId || null,
      niveauEtudeId: input.niveauEtudeId || null,
      parcoursId: input.parcoursId || null,
      classeId: input.classeId || null,
      semestre: input.semestre || null,
      folderId: folderId || null,
      metadata: null,
      uploaderId: userId,
      integrityHash: await this.computeHash(input.fichier)
    } as any);

    await AuditService.log(doc.id, userId, 'creation', { titre: input.titre, source: input.domaineCode });

    return doc;
  }

  private static async resolveFolderId(domainId: number, input: GedDocumentInput, userId: number): Promise<number | null> {
    try {
      if (!input.anneeAcademiqueId) return null;

      const AnneeModel = () => DatabaseConnection.getInstance().sequelize.model('InsAnneeAcademique') as any;
      const annee = await AnneeModel().findByPk(input.anneeAcademiqueId);
      if (!annee) return null;

      const anneeLabel = annee.libelle;

      let rootFolder = await Folder.findOne({
        where: { domainId, nom: { [Op.like]: `%${anneeLabel}%` }, parentId: { [Op.is]: null } as any, isAutoGenerated: true }
      } as any);
      if (!rootFolder) {
        rootFolder = await Folder.create({
          nom: `${anneeLabel}`, domainId, parentId: null as any, createdBy: userId, isAutoGenerated: true
        } as any);
      }

      return rootFolder.id;
    } catch {
      return null;
    }
  }

  static async generateReference(domainCode: string): Promise<string> {
    const year = new Date().getFullYear();
    const seq = Math.floor(Math.random() * 9999) + 1;
    return `${domainCode}-${year}-${String(seq).padStart(4, '0')}`;
  }

  static async computeHash(filePath: string): Promise<string> {
    try {
      const crypto = require('crypto');
      const fullPath = path.join(process.cwd(), 'public', filePath);
      if (fs.existsSync(fullPath)) {
        const fileBuffer = fs.readFileSync(fullPath);
        return crypto.createHash('sha256').update(fileBuffer).digest('hex');
      }
    } catch {}
    return '';
  }
}
