import { Model, InferAttributes, InferCreationAttributes, CreationOptional, DataTypes } from "sequelize";
import { DatabaseConnection } from "../../../core/helpers/DatabaseConnection";
import { MODULE_MODEL_PREFIX, MODULE_TABLE_PREFIX } from "../DocGenModule";

export class DocGenType extends Model<InferAttributes<DocGenType>, InferCreationAttributes<DocGenType>> {
  declare id: CreationOptional<number>
  declare code: string
  declare libelle: string
  declare categorie: string
  declare moduleSource: string
  declare description: CreationOptional<string>
  declare signatureRequired: CreationOptional<boolean>
  declare dua: CreationOptional<string>
  declare autoGenerated: CreationOptional<boolean>
  declare format: CreationOptional<string>

  declare readonly createdAt: CreationOptional<Date>
  declare readonly updatedAt: CreationOptional<Date>
}

DocGenType.init({
  id: {
    type: DataTypes.INTEGER.UNSIGNED,
    autoIncrement: true,
    primaryKey: true
  },
  code: {
    type: new DataTypes.STRING(20),
    allowNull: false,
    unique: true
  },
  libelle: {
    type: new DataTypes.STRING(200),
    allowNull: false
  },
  categorie: {
    type: new DataTypes.STRING(50),
    allowNull: false
  },
  moduleSource: {
    type: new DataTypes.STRING(50),
    allowNull: false
  },
  description: {
    type: DataTypes.TEXT,
    allowNull: true
  },
  signatureRequired: {
    type: DataTypes.BOOLEAN,
    defaultValue: false
  },
  dua: {
    type: new DataTypes.STRING(50),
    allowNull: true
  },
  autoGenerated: {
    type: DataTypes.BOOLEAN,
    defaultValue: false
  },
  format: {
    type: new DataTypes.STRING(10),
    defaultValue: 'PDF'
  },
  createdAt: DataTypes.DATE,
  updatedAt: DataTypes.DATE,
}, {
  sequelize: DatabaseConnection.getInstance().sequelize,
  modelName: MODULE_MODEL_PREFIX + 'Type',
  tableName: MODULE_TABLE_PREFIX + 'types',
  timestamps: true
})
