import { ComponentFixture, TestBed } from '@angular/core/testing';
import { RouterTestingModule } from '@angular/router/testing';
import { HttpClientTestingModule } from '@angular/common/http/testing';
import { TypesPageComponent } from './types-page.component';
import { DocGenTypeService } from 'src/app/data/modules/docgen/services/docgen-type.service';
import { of } from 'rxjs';

describe('TypesPageComponent', () => {
  let component: TypesPageComponent;
  let fixture: ComponentFixture<TypesPageComponent>;

  beforeEach(async () => {
    const typeServiceSpy = jasmine.createSpyObj('DocGenTypeService', ['getAll', 'create', 'update', 'delete']);
    typeServiceSpy.getAll.and.returnValue(of([{ id: '1', code: 'BULLETIN', libelle: 'Bulletin', categorie: 'Notes' }]));

    await TestBed.configureTestingModule({
      declarations: [TypesPageComponent],
      imports: [RouterTestingModule, HttpClientTestingModule],
      providers: [{ provide: DocGenTypeService, useValue: typeServiceSpy }]
    }).compileComponents();
  });

  beforeEach(() => {
    fixture = TestBed.createComponent(TypesPageComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  it('should create', () => expect(component).toBeTruthy());

  it('charge les types au démarrage', () => {
    expect(component.types.length).toBe(1);
    expect(component.types[0].code).toBe('BULLETIN');
  });

  it('ouvrirFormulaire initialise formData pour un nouveau type', () => {
    component.ouvrirFormulaire();
    expect(component.editingId).toBeNull();
    expect(component.showForm).toBeTrue();
    expect(component.formData.code).toBe('');
  });

  it('ouvrirFormulaire préremplit pour édition', () => {
    const type = { id: '2', code: 'CERTIF', libelle: 'Certificat', categorie: 'Scolarité', signatureRequired: true, autoGenerated: false, format: 'PDF' };
    component.ouvrirFormulaire(type);
    expect(component.editingId).toBe('2');
    expect(component.formData.code).toBe('CERTIF');
  });

  it('filtrer par catégorie', () => {
    component.types = [
      { id: '1', code: 'A', libelle: 'Type A', categorie: 'Notes' },
      { id: '2', code: 'B', libelle: 'Type B', categorie: 'Examens' }
    ] as any;
    component.selectedCategorie = 'Notes';
    component.filtrer();
    expect(component.filteredTypes.length).toBe(1);
    expect(component.filteredTypes[0].code).toBe('A');
  });

  it('filtrer par recherche', () => {
    component.types = [
      { id: '1', code: 'BULLETIN', libelle: 'Bulletin de notes' },
      { id: '2', code: 'CERTIF', libelle: 'Certificat' }
    ] as any;
    component.search = 'certif';
    component.filtrer();
    expect(component.filteredTypes.length).toBe(1);
  });

  it('getBadgeColor retourne une couleur', () => {
    expect(component.getBadgeColor('Examens')).toBe('orange');
    expect(component.getBadgeColor('Inconnu')).toBe('gray');
    expect(component.getBadgeColor()).toBe('gray');
  });
});
