import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { BaseComponentClass } from 'src/app/core/base-component-class';
import { DocGenTypeService } from 'src/app/data/modules/docgen/services/docgen-type.service';
import { DocGenType } from 'src/app/data/modules/docgen/models/DocGenType.model';

@Component({
  selector: 'app-types-page',
  templateUrl: './types-page.component.html',
  styleUrls: ['./types-page.component.scss']
})
export class TypesPageComponent extends BaseComponentClass implements OnInit {
  types: DocGenType[] = [];
  filteredTypes: DocGenType[] = [];
  categories: string[] = [];
  selectedCategorie: string = '';
  search: string = '';
  loading = false;
  showForm = false;
  editingId: string | null = null;
  formData: Partial<DocGenType> = {};

  constructor(
    private typeService: DocGenTypeService,
    private router: Router,
  ) { super(); }

  ngOnInit(): void { this.getTypes(); }

  getTypes(): void {
    this.loading = true;
    this.typeService.getAll().subscribe({
      next: (res) => {
        this.types = res;
        this.categories = [...new Set(res.map(t => t.categorie || ''))].filter(Boolean).sort();
        this.filtrer();
        this.loading = false;
      },
      error: () => this.loading = false
    });
  }

  filtrer(): void {
    this.filteredTypes = this.types.filter(t => {
      if (this.selectedCategorie && t.categorie !== this.selectedCategorie) return false;
      if (this.search && !t.libelle?.toLowerCase().includes(this.search.toLowerCase()) && !t.code?.toLowerCase().includes(this.search.toLowerCase())) return false;
      return true;
    });
  }

  ouvrirFormulaire(type?: DocGenType): void {
    this.editingId = type?.id || null;
    this.formData = type ? { ...type } : { code: '', libelle: '', categorie: '', moduleSource: '', signatureRequired: false, autoGenerated: false, format: 'PDF' };
    this.showForm = true;
  }

  fermerFormulaire(): void { this.showForm = false; this.editingId = null; }

  sauvegarder(): void {
    if (!this.formData.code || !this.formData.libelle) return;
    if (this.editingId) {
      this.typeService.update(this.editingId, this.formData).subscribe({ next: () => { this.fermerFormulaire(); this.getTypes(); } });
    } else {
      this.typeService.create(this.formData).subscribe({ next: () => { this.fermerFormulaire(); this.getTypes(); } });
    }
  }

  supprimer(id?: string): void {
    if (!id || !confirm('Supprimer ce type de document ?')) return;
    this.typeService.delete(id).subscribe({ next: () => this.getTypes() });
  }

  getBadgeColor(categorie?: string): string {
    const colors: any = { 'Admissions': 'blue', 'Inscriptions': 'green', 'Scolarité': 'purple', 'Examens': 'orange', 'Notes': 'red', 'Délibérations': 'pink', 'Diplômes': 'yellow', 'Finance': 'emerald' };
    return categorie ? (colors[categorie] || 'gray') : 'gray';
  }
}
