CREATE TABLE IF NOT EXISTS `brs_configurations` (`id` INTEGER UNSIGNED auto_increment , `nom` VARCHAR(150) NOT NULL, `type` ENUM('TOTAL', 'PARTIELLE') NOT NULL, `taux` DECIMAL(5,2) NOT NULL, `description` TEXT, `statut` ENUM('ACTIVE', 'INACTIVE') NOT NULL DEFAULT 'ACTIVE', `createdAt` DATETIME, `updatedAt` DATETIME, `deletedAt` DATETIME, PRIMARY KEY (`id`)) ENGINE=InnoDB COLLATE utf8mb3_general_ci;;
CREATE TABLE IF NOT EXISTS `brs_attributions` (`id` INTEGER UNSIGNED auto_increment , `dossierEtudiantId` INTEGER UNSIGNED NOT NULL, `configurationId` INTEGER UNSIGNED NOT NULL, `niveauEtudeId` INTEGER UNSIGNED DEFAULT NULL COMMENT 'Niveau d\'études ciblé (L1, M1, etc.) — renseigné lors d\'une attribution par campagne', `type` ENUM('TOTAL', 'PARTIELLE') NOT NULL, `taux` DECIMAL(5,2) NOT NULL, `dateDebut` DATE NOT NULL, `dateFin` DATE DEFAULT NULL, `statut` ENUM('ACTIVE', 'SUSPENDUE', 'EXPIREE') NOT NULL DEFAULT 'ACTIVE', `motif` TEXT, `valideParId` INTEGER UNSIGNED NOT NULL, `createdAt` DATETIME, `updatedAt` DATETIME, `deletedAt` DATETIME, PRIMARY KEY (`id`), FOREIGN KEY (`dossierEtudiantId`) REFERENCES `ins_dossiers_etudiants` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE, FOREIGN KEY (`configurationId`) REFERENCES `brs_configurations` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE, FOREIGN KEY (`niveauEtudeId`) REFERENCES `ins_niveaux_etudes` (`id`) ON DELETE SET NULL ON UPDATE CASCADE, FOREIGN KEY (`valideParId`) REFERENCES `aut_utilisateurs` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE) ENGINE=InnoDB COLLATE utf8mb3_general_ci;;
CREATE TABLE IF NOT EXISTS `rpt_documents_academiques` (`id` INTEGER UNSIGNED auto_increment , `typeDocument` VARCHAR(255), `periode` VARCHAR(255), `nbDemandes` INTEGER DEFAULT 0, `nbDelivres` INTEGER DEFAULT 0, `createdAt` DATETIME, `updatedAt` DATETIME, PRIMARY KEY (`id`)) ENGINE=InnoDB COLLATE utf8mb3_general_ci;;
CREATE TABLE IF NOT EXISTS `rpt_effectifs_rh` (`id` INTEGER UNSIGNED auto_increment , `departementId` INTEGER UNSIGNED, `date` DATE, `nbEmployes` INTEGER DEFAULT 0, `nbActifs` INTEGER DEFAULT 0, `masseSalariale` DECIMAL(12,2) DEFAULT 0, `createdAt` DATETIME, `updatedAt` DATETIME, PRIMARY KEY (`id`)) ENGINE=InnoDB COLLATE utf8mb3_general_ci;;
CREATE TABLE IF NOT EXISTS `rpt_factures` (`id` INTEGER UNSIGNED auto_increment , `mois` VARCHAR(255), `nbFactures` INTEGER DEFAULT 0, `montantTotal` DECIMAL(12,2) DEFAULT 0, `statut` VARCHAR(255), `createdAt` DATETIME, `updatedAt` DATETIME, PRIMARY KEY (`id`)) ENGINE=InnoDB COLLATE utf8mb3_general_ci;;
CREATE TABLE IF NOT EXISTS `rpt_paie` (`id` INTEGER UNSIGNED auto_increment , `periode` VARCHAR(255), `nbBulletins` INTEGER DEFAULT 0, `totalGains` DECIMAL(12,2) DEFAULT 0, `totalRetenues` DECIMAL(12,2) DEFAULT 0, `netTotal` DECIMAL(12,2) DEFAULT 0, `createdAt` DATETIME, `updatedAt` DATETIME, PRIMARY KEY (`id`)) ENGINE=InnoDB COLLATE utf8mb3_general_ci;;
CREATE TABLE IF NOT EXISTS `rpt_presences` (`id` INTEGER UNSIGNED auto_increment , `coursId` INTEGER UNSIGNED, `seanceId` INTEGER UNSIGNED, `date` DATE, `nbPresent` INTEGER DEFAULT 0, `nbAbsent` INTEGER DEFAULT 0, `taux` FLOAT DEFAULT 0, `createdAt` DATETIME, `updatedAt` DATETIME, PRIMARY KEY (`id`)) ENGINE=InnoDB COLLATE utf8mb3_general_ci;;
ALTER TABLE `ged_documents` CHANGE `titre` `titre` VARCHAR(255) NOT NULL;;
ALTER TABLE `ged_documents` CHANGE `reference` `reference` VARCHAR(255);;
ALTER TABLE `ged_documents` CHANGE `eleve` `eleve` VARCHAR(255);;
ALTER TABLE `ged_documents` CHANGE `parcours` `parcours` VARCHAR(255);;
ALTER TABLE `ged_documents` CHANGE `categorie` `categorie` VARCHAR(255);;
ALTER TABLE `ged_documents` CHANGE `tags` `tags` TEXT;;
ALTER TABLE `ged_documents` CHANGE `nommage` `nommage` VARCHAR(255);;
ALTER TABLE `ged_documents` CHANGE `type` `type` VARCHAR(255) DEFAULT 'PDF';;
ALTER TABLE `ged_documents` CHANGE `statut` `statut` VARCHAR(255) NOT NULL DEFAULT 'Disponible';;
ALTER TABLE `ged_documents` CHANGE `fichier` `fichier` VARCHAR(255) NOT NULL;;
ALTER TABLE `ged_documents` CHANGE `dureeConservation` `dureeConservation` VARCHAR(255);;
ALTER TABLE `ged_documents` CHANGE `archivedUntil` `archivedUntil` DATETIME;;
ALTER TABLE `ged_documents` CHANGE `isArchived` `isArchived` TINYINT(1) NOT NULL DEFAULT false;;
ALTER TABLE `ged_documents` DROP FOREIGN KEY `ged_documents_ibfk_161`;;
ALTER TABLE `ged_documents` ADD FOREIGN KEY (`domainId`) REFERENCES `ged_domains` (`id`) ON DELETE SET NULL ON UPDATE CASCADE;;
ALTER TABLE `ged_documents` DROP FOREIGN KEY `ged_documents_ibfk_162`;;
ALTER TABLE `ged_documents` ADD FOREIGN KEY (`documentTypeId`) REFERENCES `ged_document_types` (`id`) ON DELETE SET NULL ON UPDATE CASCADE;;
ALTER TABLE `ged_documents` CHANGE `classificationPath` `classificationPath` VARCHAR(255);;
ALTER TABLE `ged_documents` CHANGE `sourceType` `sourceType` ENUM('genere_application', 'numerise_interne', 'recu_externe', 'document_sortant') NOT NULL DEFAULT 'numerise_interne';;
ALTER TABLE `ged_documents` CHANGE `externalIssuer` `externalIssuer` VARCHAR(255);;
ALTER TABLE `ged_documents` CHANGE `receptionDate` `receptionDate` DATE;;
ALTER TABLE `ged_documents` CHANGE `confidentialityLevel` `confidentialityLevel` ENUM('public', 'interne', 'restreint', 'confidentiel') NOT NULL DEFAULT 'interne';;
ALTER TABLE `ged_documents` CHANGE `lifecycleStatus` `lifecycleStatus` ENUM('courant', 'intermediaire', 'definitif', 'a_detruire') NOT NULL DEFAULT 'courant';;
ALTER TABLE `ged_documents` CHANGE `duaEndDate` `duaEndDate` DATE;;
ALTER TABLE `ged_documents` CHANGE `integrityHash` `integrityHash` VARCHAR(64);;
ALTER TABLE `ged_documents` CHANGE `versionMajor` `versionMajor` INTEGER NOT NULL DEFAULT 1;;
ALTER TABLE `ged_documents` CHANGE `versionMinor` `versionMinor` INTEGER NOT NULL DEFAULT 0;;
ALTER TABLE `ged_documents` CHANGE `versionComment` `versionComment` VARCHAR(255);;
ALTER TABLE `ged_documents` DROP FOREIGN KEY `ged_documents_ibfk_163`;;
ALTER TABLE `ged_documents` ADD FOREIGN KEY (`parentDocumentId`) REFERENCES `ged_documents` (`id`) ON DELETE SET NULL ON UPDATE CASCADE;;
ALTER TABLE `ged_documents` CHANGE `isCurrentVersion` `isCurrentVersion` TINYINT(1) NOT NULL DEFAULT true;;
ALTER TABLE `ged_documents` CHANGE `isLocked` `isLocked` TINYINT(1) NOT NULL DEFAULT false;;
ALTER TABLE `ged_documents` DROP FOREIGN KEY `ged_documents_ibfk_164`;;
ALTER TABLE `ged_documents` DROP FOREIGN KEY `ged_documents_ibfk_168`;;
ALTER TABLE `ged_documents` ADD FOREIGN KEY (`lockedBy`) REFERENCES `aut_utilisateurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE;;
ALTER TABLE `ged_documents` CHANGE `lockedAt` `lockedAt` DATETIME;;
ALTER TABLE `ged_documents` DROP FOREIGN KEY `ged_documents_ibfk_165`;;
ALTER TABLE `ged_documents` ADD FOREIGN KEY (`processus_generateur_id`) REFERENCES `ged_processus` (`id`) ON DELETE SET NULL ON UPDATE CASCADE;;
ALTER TABLE `ged_documents` CHANGE `storage_location` `storage_location` VARCHAR(50) NOT NULL DEFAULT 'local';;
ALTER TABLE `ged_documents` CHANGE `is_encrypted` `is_encrypted` TINYINT(1) NOT NULL DEFAULT false;;
ALTER TABLE `ged_documents` CHANGE `encryption_key_id` `encryption_key_id` VARCHAR(255);;
ALTER TABLE `ged_documents` CHANGE `anneeAcademiqueId` `anneeAcademiqueId` INTEGER UNSIGNED;;
ALTER TABLE `ged_documents` CHANGE `parcoursId` `parcoursId` INTEGER UNSIGNED;;
ALTER TABLE `ged_documents` CHANGE `niveauEtudeId` `niveauEtudeId` INTEGER UNSIGNED;;
ALTER TABLE `ged_documents` CHANGE `semestre` `semestre` ENUM('semestre1', 'semestre2', 'semestre3', 'semestre4', 'semestre5', 'semestre6');;
ALTER TABLE `ged_documents` CHANGE `classeId` `classeId` INTEGER UNSIGNED;;
ALTER TABLE `ged_documents` CHANGE `salleId` `salleId` INTEGER UNSIGNED;;
ALTER TABLE `ged_documents` CHANGE `cursusApprenantId` `cursusApprenantId` INTEGER UNSIGNED;;
ALTER TABLE `ged_documents` CHANGE `inscriptionDossierId` `inscriptionDossierId` INTEGER UNSIGNED;;
ALTER TABLE `ged_documents` CHANGE `bulletinId` `bulletinId` INTEGER UNSIGNED;;
ALTER TABLE `ged_documents` CHANGE `bordereauId` `bordereauId` INTEGER UNSIGNED;;
ALTER TABLE `ged_documents` DROP FOREIGN KEY `ged_documents_ibfk_166`;;
ALTER TABLE `ged_documents` ADD FOREIGN KEY (`folderId`) REFERENCES `ged_folders` (`id`) ON DELETE SET NULL ON UPDATE CASCADE;;
ALTER TABLE `ged_documents` DROP FOREIGN KEY `ged_documents_ibfk_167`;;
ALTER TABLE `ged_documents` ADD FOREIGN KEY (`sessionId`) REFERENCES `ged_sessions` (`id`) ON DELETE SET NULL ON UPDATE CASCADE;;
ALTER TABLE `ged_documents` CHANGE `metadata` `metadata` TEXT;;
ALTER TABLE `ged_documents` CHANGE `taille` `taille` VARCHAR(255);;
ALTER TABLE `ged_documents` ADD FOREIGN KEY (`uploaderId`) REFERENCES `aut_utilisateurs` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;;
ALTER TABLE `ged_documents` CHANGE `nbPages` `nbPages` INTEGER;;
ALTER TABLE `ged_documents` CHANGE `auteur` `auteur` VARCHAR(255);;
ALTER TABLE `ged_documents` CHANGE `dateDocument` `dateDocument` DATE;;
ALTER TABLE `ged_documents` CHANGE `contenuTexte` `contenuTexte` LONGTEXT;;
ALTER TABLE `ged_documents` CHANGE `destinataire` `destinataire` VARCHAR(255);;
ALTER TABLE `ged_documents` CHANGE `dateEnvoi` `dateEnvoi` DATE;;
ALTER TABLE `ged_documents` CHANGE `modeEnvoi` `modeEnvoi` ENUM('courrier', 'email', 'remise_main_propre', 'fax');;
ALTER TABLE `ged_documents` CHANGE `accuseReception` `accuseReception` TINYINT(1) NOT NULL DEFAULT false;;
ALTER TABLE `ged_documents` CHANGE `numeroCourrier` `numeroCourrier` VARCHAR(50);;
ALTER TABLE `ged_documents` CHANGE `verificationCode` `verificationCode` VARCHAR(8);;
ALTER TABLE `ged_documents` CHANGE `createdAt` `createdAt` DATETIME;;
ALTER TABLE `ged_documents` CHANGE `updatedAt` `updatedAt` DATETIME;;
ALTER TABLE `ged_documents` CHANGE `deletedAt` `deletedAt` DATETIME;;
ALTER TABLE `ged_processus` CHANGE `code` `code` VARCHAR(50) NOT NULL;;
ALTER TABLE `ged_processus` CHANGE `libelle` `libelle` VARCHAR(150) NOT NULL;;
ALTER TABLE `ged_processus` CHANGE `description` `description` TEXT;;
ALTER TABLE `ged_processus` CHANGE `module_source` `module_source` VARCHAR(50);;
ALTER TABLE `ged_processus` CHANGE `is_actif` `is_actif` TINYINT(1) NOT NULL DEFAULT true;;
ALTER TABLE `ged_processus` CHANGE `created_at` `created_at` DATETIME;;
ALTER TABLE `ged_processus` CHANGE `updated_at` `updated_at` DATETIME;;
